"""add support for interviews

Revision ID: 17f1c636065a
Revises: 76b2414893b9
Create Date: 2025-09-28 16:22:38.032570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f1c636065a'
down_revision: Union[str, None] = '76b2414893b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('offer_details', sa.Text(), nullable=True))
    op.add_column('job_applications', sa.Column('offer_salary', sa.Float(), nullable=True))
    op.add_column('job_applications', sa.Column('offer_expiry_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'offer_expiry_date')
    op.drop_column('job_applications', 'offer_salary')
    op.drop_column('job_applications', 'offer_details')
    # ### end Alembic commands ###
