"""user roles using is_supervisor v-2

Revision ID: 8312b45de74b
Revises: 8f4c178564fd
Create Date: 2025-09-23 20:35:33.389296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8312b45de74b'
down_revision: Union[str, None] = '8f4c178564fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
