"""job application support v-1

Revision ID: 8f4c178564fd
Revises: e33bb845793c
Create Date: 2025-09-23 19:29:01.857489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4c178564fd'
down_revision: Union[str, None] = 'e33bb845793c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_supervisor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_supervisor')
    # ### end Alembic commands ###
